### ISSUE TITLE
Example is too complicated

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/mbed-client-quickstart#35]
This example needs to be simplified, 50 lines or less for a golden example. Its too long and too complicated to expect people to use. It needs to be wrapped up behind a simple interface library.

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTCLT-413

**Comment by teetak01** [comment]
Current example demonstrates several functionalities of the client and as such cannot be implemented in much shorter format. Should there be another simpler example to demonstrate minimal functionality?

**Comment by BlackstoneEngineering** [comment]
@teetak01 the Apps team is moving forward with more concise examples, Its on our list for january, no worries. Something that is clearer, like this : https://github.com/BlackstoneEngineering/mbed-client-examples

note the simplification of the code and the heavy commenting. It was used in the meetup documented here : https://www.youtube.com/watch?v=nWz9Toe8nJE

**Comment by janjongboom** [comment]
Clearer example is now here: http://github.com/ARMmbed/mbed-client-mbedos-example/ although we need to think of upgrade path. Maybe merge that back in this repo?

**Comment by teetak01** [comment]
In my opinion the mbed-client-examples is a bit confusingly named as it does not work on linux. Maybe the new name is better?

There are now two different naming schemes, we have:

https://github.com/ARMmbed/mbed-client-example-6lowpan

and

https://github.com/ARMmbed/mbed-client-linux-example

Maybe formalize the naming along similar lines, for. ex. mbed-client-example-XXX

**Comment by anttiylitokola** [comment]
Clearer example is taken into use. This can be closed now.
