### ISSUE TITLE
Rename module in module.json

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-client-quickstart#55]
In module.json, the project is named "mbed-client-examples". The executable created then named "mbed-client-examples.bin"

This is a little confusing since the repository has been renamed to "mbed-client-quickstart".

Can we rename this? Or do other things rely on this name? Those dependents should get updated before changing this.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-613

**Comment by BlackstoneEngineering** [comment]
Already on the todo list, @janjongboom is taking care of it tomorrow

**Comment by teetak01** [comment]
https://github.com/ARMmbed/mbed-client-quickstart/pull/61

**Comment by teetak01** [comment]
Closing issue as name has been changed.
