### ISSUE TITLE
No context on how to access POST Payload

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/mbed-client-quickstart#66]
## Problem
The post payload is not accessed

## Solution
Add example code showing how to access the POST payload.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-743

**Comment by anttiylitokola** [comment]
Hi, example code added how to use post payloads. https://github.com/ARMmbed/mbed-client-quickstart/pull/74
