### ISSUE TITLE
Secure Connection Failed Error

### ISSUE THREAD

**Issue by emilijatasic** [ARMmbed/mbed-client-quickstart#67]
Hello. 
I have been trying to run this example, following the instructions on readme (c/p security credentials, etc.) , but I keep getting this error. 
 I am using a university network. 
![error](https://cloud.githubusercontent.com/assets/19814880/15976845/819c1c18-2f55-11e6-8f05-f81d098a1b4e.jpg)

Thanks!

**Comment by yogpan01** [comment]
Hi,
It seems that there is issue with DTLS Handshake on UDP , did you try using TCP mode ? You can change socket mode by following these instructions https://github.com/ARMmbed/mbed-client-quickstart/blob/master/README.md#Setting-socket-type

**Comment by emilijatasic** [comment]
I tried that too, but with same result

**Comment by yogpan01** [comment]
You can also try to build the log enabled build . 
Try building with "yotta build -d" , this should enable detailed logs , which might reveal some more information about this error.

**Comment by emilijatasic** [comment]
Ok, I will try that, thanks! 
I will update this topic on monday.

**Comment by emilijatasic** [comment]
So I just tried to build with yotta build -d, and got this error on terminal(in bunch of other information):

[ERR ][mClt]: M2MConnectionSecurityPimpl::timer_expired - handshake timeout

What does that mean , or - what should I do to solve this issue?

**Comment by teetak01** [comment]
Hi, do you know if the university network has the port 5684 open? It might be that connector is unable to respond.

**Comment by emilijatasic** [comment]
The port 5684 hasn't been open, but now it is and everything works now. Thanks
