### ISSUE TITLE
yt target frdm-k64f-armcc build fail

### ISSUE THREAD

**Issue by jsplyy** [ARMmbed/mbed-client-quickstart#71]
I want to debug the mbed os in keil. So I build it in armcc target.
But it fail. 

![capture11](https://cloud.githubusercontent.com/assets/3600912/16651113/8388c16e-4474-11e6-9014-4311869fddf6.PNG)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-854

**Comment by jsplyy** [comment]
@ciarmcom  what's mean?

**Comment by yogpan01** [comment]
Hi, 
Do you have ARM Compiler installed ? You need to install it .
Here is the link 
https://developer.arm.com/products/software-development-tools/compilers/arm-compiler-5/downloads

Remember this is a commercial compiler so you would need proper license as well. Check the link, it has description about it.

**Comment by jsplyy** [comment]
@yogpan01  Hi.
Now, I have installed keil-mdk and could use armcc compile.
But when I debug,the mdk does not appear as descriped in docs.
![captured](https://cloud.githubusercontent.com/assets/3600912/17204891/9f6a9238-54da-11e6-9416-14333c5fa32f.PNG)

**Comment by jsplyy** [comment]
I want use an IDE to develop mbed os.
which is supported and how to support it ?

**Comment by jsplyy** [comment]
When will Online compiler be revamped?

**Comment by teetak01** [comment]
@jsplyy Hi, the Yotta-based example does not directly support any IDE's. 

Also, have you taken a look to our newer example program using the latest mbed-os? https://github.com/armmbed/mbed-os-example-client

Its build-environment also supports IDE integration: https://github.com/armmbed/mbed-cli#exporting-to-desktop-ides

Do you still have any issues related to this repository or can this be closed?
