### ISSUE TITLE
multi k64 boards connect to connector server error.[ERROR:] M2MInterface::InvalidParameters

### ISSUE THREAD

**Issue by jsplyy** [ARMmbed/mbed-client-quickstart#73]
I try to connect multi boards to connector server.
If I do not modify the MBED_ENDPOINT_NAME "277683b2-0468-4690-a7b5-582129057200",it will show one device in connector server.
But if I modify the MBED_ENDPOINT_NAME "277683b2-0468-4690-a7b6-582129057200",it will show error[ERROR:] M2MInterface::InvalidParameters

What's the relationship between mbed endpoint name and mbed domain?
![6](https://cloud.githubusercontent.com/assets/3600912/16804017/35eef1a4-493c-11e6-88b1-e112c05ff4e3.PNG)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-857

**Comment by yogpan01** [comment]
Hi,
You cannot modify endpoint name yourself, those endpoint names are embedded into certificates , so if those are mismatching ,server will not accept those endpoints as valid ones, hence the errors.
You need unique security.h for each devices.

**Comment by jsplyy** [comment]
hmm...
I want to connect multi boards. How to do?

**Comment by anttiylitokola** [comment]
Hi, you can create a new security.h for every board you need. Just click the "GET MY SECURITY CREDENTIALS" button in Connector website. It will create a new security.h containing unique endpoint name. So every board must have unique security.h.
